[options]
admin_passwd = admin123
addons_path = /home/jihad/Documents/DEV/UniERP/addons

db_host = localhost
db_port = 5432
db_user = unierp
db_password = unierp

http_port = 8019
longpolling_port = 8072
