#!/bin/sh

set -e

UNIERP_CONFIGURATION_FILE=/etc/unierp/unierp.conf
UNIERP_GROUP="unierp"
UNIERP_DATA_DIR=/var/lib/unierp
UNIERP_LOG_DIR=/var/log/unierp
UNIERP_USER="unierp"
GSFONTS_DIR=/usr/share/fonts/type1/gsfonts

case "${1}" in
    configure)
        if ! getent passwd | grep -q "^unierp:"; then
            adduser --system --home $UNIERP_DATA_DIR --quiet --group $UNIERP_USER
            # Data dir
            chown $UNIERP_USER:$UNIERP_GROUP $UNIERP_DATA_DIR
        fi
        # Register "$UNIERP_USER" as a postgres user with "Create DB" role attribute
        su - postgres -c "createuser -d -R -S $UNIERP_USER" 2> /dev/null || true
        # Configuration file
        chown $UNIERP_USER:$UNIERP_GROUP $UNIERP_CONFIGURATION_FILE
        chmod 0640 $UNIERP_CONFIGURATION_FILE
        # Log
        mkdir -p $UNIERP_LOG_DIR
        chown $UNIERP_USER:$UNIERP_GROUP $UNIERP_LOG_DIR
        chmod 0750 $UNIERP_LOG_DIR
        	# work around https://bugs.debian.org/1059326

        if ! [ -e ${GSFONTS_DIR}/n021003l.pfb ] ; then
            if ! [ -d ${GSFONTS_DIR} ] ; then
                mkdir ${GSFONTS_DIR}
                touch ${GSFONTS_DIR}/.created-by-unierp-package
            fi
            ln -s /usr/share/fonts/X11/Type1/C059-Roman.pfb ${GSFONTS_DIR}/n021003l.pfb
        fi
        ;;
    *)
        ;;
esac

#DEBHELPER#

exit 0
