#!/bin/sh

set -e

UNIERP_LIB_DIR=/var/lib/unierp
UNIERP_USER="unierp"
UNIERP_GROUP="unierp"
GSFONTS_DIR=/usr/share/fonts/type1/gsfonts

case "${1}" in
    remove)
        deluser --quiet --system $UNIERP_USER || true
        delgroup --quiet --system --only-if-empty $UNIERP_GROUP || true
        	# remove workaround for https://bugs.debian.org/1059326
        if [ -L ${GSFONTS_DIR}/n021003l.pfb ] ; then
            rm ${GSFONTS_DIR}/n021003l.pfb
            if [ "$(ls -A ${GSFONTS_DIR})" = ".created-by-unierp-package" ] ; then
                rm -fr ${GSFONTS_DIR}
            fi
    	fi
        ;;

    purge)
        if [ -d "$UNIERP_LIB_DIR" ]; then
            rm -rf $UNIERP_LIB_DIR
        fi
        ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

esac

#DEBHELPER#

exit 0
